### ISSUE TITLE
DANDAOTrade contracts are missing

### ISSUE THREAD

**Issue by researchergurl** [dandao2022/swapbot#2]
Could you please include them? They are unverified on etherscan too so can't find source..

**Comment by researchergurl** [comment]
@dandao2022

**Comment by researchergurl** [comment]
@dandao2022 would appreciate

**Comment by dandao2022** [comment]
added https://github.com/dandao2022/swapbot/commit/c5d84a5f0c9e2f7e0afbfcc97dcecf15307a6ece
